#!/bin/bash
#
# Return the remote host OpenSSH version banner and disconnects after one
# second.
#
OURVERSION="SSH-2.0-OpenSSH_5";
NC="`which nc`";
NCARGS="-w 1 -r";
HEAD="`which head`";
HEADARGS=" -n 1";
VERSION="3.1";

help() {
    echo "protocol_banner_scanner version $VERSION";
    echo "Return the remote host OpenSSH version banner and disconnect";
    echo "$0 host port";
    exit 1;
}

if [ ! "$#" == "2" ];
then
    help;
else
    HOST="$1";
    PORT="$2";
fi

fp() {
    echo "$OURVERSION" | $NC $NCARGS $HOST $PORT | $HEAD$HEADARGS;
}

main() {
    REMOTEVERSION=`fp`;
    echo "The remote server reports the following OpenSSH version: $REMOTEVERSION";
}

main;
